In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("car_prediction_data.csv")

In [3]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
df.tail()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
296,city,2016,9.50,11.6,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.9,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,0

In [5]:
df['Owner'].value_counts()

Owner
0    290
1     10
3      1
Name: count, dtype: int64

In [6]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [7]:
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven',
       'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [8]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [9]:
df['Seller_Type'].value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

In [10]:
len(df['Car_Name'].value_counts())

98

In [11]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

In [12]:
df['Transmission'].value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [13]:
df['Owner'].value_counts()

Owner
0    290
1     10
3      1
Name: count, dtype: int64

I don't need Car name and year so i just drop those

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [15]:
df.drop(columns=['Car_Name','Year'],axis=1,inplace=True)

In [16]:
df.head()

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Present_Price  301 non-null    float64
 2   Kms_Driven     301 non-null    int64
 3   Fuel_Type      301 non-null    object
 4   Seller_Type    301 non-null    object
 5   Transmission   301 non-null    object
 6   Owner          301 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 16.6+ KB

In [18]:
df.head()

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [19]:
X=df.drop('Present_Price',axis=1)
y=df['Present_Price']

In [20]:
X.head()

   Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0           3.35       27000    Petrol      Dealer       Manual      0
1           4.75       43000    Diesel      Dealer       Manual      0
2           7.25        6900    Petrol      Dealer       Manual      0
3           2.85        5200    Petrol      Dealer       Manual      0
4           4.60       42450    Diesel      Dealer       Manual      0

In [21]:
y

0       5.59
1       9.54
2       9.85
3       4.15
4       6.87
       ...
296    11.60
297     5.90
298    11.00
299    12.50
300     5.90
Name: Present_Price, Length: 301, dtype: float64

### Dividing the categorical and num features and merging them using columnTransformer

In [22]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Kms_Driven     301 non-null    int64
 2   Fuel_Type      301 non-null    object
 3   Seller_Type    301 non-null    object
 4   Transmission   301 non-null    object
 5   Owner          301 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 14.2+ KB

In [23]:
num=X.select_dtypes(exclude=['object']).columns
cat=X.select_dtypes(include=['object']).columns

In [24]:
num

Index(['Selling_Price', 'Kms_Driven', 'Owner'], dtype='object')

In [25]:
cat

Index(['Fuel_Type', 'Seller_Type', 'Transmission'], dtype='object')

In [26]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

onehot=OneHotEncoder(drop='if_binary')
scaler=StandardScaler()

preprocessor=ColumnTransformer(
    transformers=[
        ('onehottransformer',onehot,cat),
        ('numtransformer',scaler,num)
    ],remainder='passthrough'
)

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
X_train

     Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
184           0.25       26000    Petrol  Individual       Manual      1
132           0.75        3500    Petrol  Individual       Manual      0
194           0.20       50000    Petrol  Individual       Manual      0
75            3.95       36000    Petrol      Dealer       Manual      0
111           1.15        8700    Petrol  Individual       Manual      0
..             ...         ...       ...         ...          ...    ...
188           0.25       18000    Petrol  Individual       Manual      0
71            4.50       45000    Diesel      Dealer       Manual      0
106           1.35       16500    Petrol  Individual       Manual      1
270           4.10       69341    Petrol      Dealer       Manual      0
102           1.65        4000    Petrol  Individual       Manual      0

[240 rows x 6 columns]

In [29]:
y_train

184     0.750
132     0.950
194     0.787
75      6.800
111     1.500
        ...
188     0.570
71     12.480
106     3.450
270    10.000
102     1.780
Name: Present_Price, Length: 240, dtype: float64

In [30]:
y_test

177     0.57
289    13.60
228     9.40
198     0.57
60     18.61
       ...
234     5.70
296    11.60
281     7.60
285     8.50
182     0.58
Name: Present_Price, Length: 61, dtype: float64

In [31]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

In [32]:
X_train

array([[ 0.        ,  0.        ,  1.        , ..., -0.85424928,
        -0.27555466,  3.52821143],
       [ 0.        ,  0.        ,  1.        , ..., -0.75700513,
        -0.81428242, -0.18569534],
       [ 0.        ,  0.        ,  1.        , ..., -0.86397369,
         0.29908829, -0.18569534],
       ...,
       [ 0.        ,  0.        ,  1.        , ..., -0.64031216,
        -0.50301749,  3.52821143],
       [ 0.        ,  0.        ,  1.        , ..., -0.10546938,
         0.76217867, -0.18569534],
       [ 0.        ,  0.        ,  1.        , ..., -0.58196568,
        -0.8023107 , -0.18569534]], shape=(240, 8))

In [33]:
X_test

array([[ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        -0.83480045, -0.32344157, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         1.06340522, -0.63518537, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.05984567,  0.53852285, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.8736981 , -0.06006356,  3.52821143],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.44882224,  0.05967767, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.54606638,  0.11632788, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.68893423, -0.27555466, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.8056272 , -0.70653687, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.81535162, -0.56287614, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.26405837,  0.179371  , -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.89614529, -0.84849762, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.68893423, -0.10795047, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.55579079, -0.53893268, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        -0.82507603, -0.86695803, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.29323161,  0.179371  , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.38747739,  0.64703459, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.71810748, -0.62273478, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         2.40342951, -0.68977645, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.80951697, -0.6921708 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.57224126, -0.86456368, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.82118627, -0.61076305, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.72110584, -0.43276739, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.13764098, -0.12418413, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.31940649, -0.4192154 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.78617838, -0.29949812, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.17354028, -0.06006356, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.06957008,  0.45953339, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.38747739,  0.13148409, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.6694854 , -0.6347065 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.6694854 , -0.46710231, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.77645396, -0.51498922, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.70165701,  0.61035322, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.81535162, -0.25161121, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.52361919,  0.49063593, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.60441287,  0.13148409, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.1929891 , -0.06006356, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.16681422,  0.82584432, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.16381586,  0.58640976, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.33885532,  0.46379532, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.02094801,  0.29908829, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.22021746,  0.89767469, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        -0.61113892,  2.33796935, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.02767406, -0.44315885, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.82118627,  0.10754064, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.36130251, -0.09767873, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.78617838, -0.13189392, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.31268044,  0.0626706 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.11819215,  1.01739197, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.1249182 , -0.17978084, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        -0.29995766,  0.35013573, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.09096379, -0.0313793 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.64031216, -0.79991635, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         3.66760336,  0.22725792, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         3.57035922, -0.53893268, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.70165701,  0.57158876, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.21705096, -0.16175141, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.16681422, -0.79053052, -0.18569534],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.94476736, -0.08429433, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
        -0.49444595,  0.3100065 , -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.53634197, -0.53752002, -0.18569534],
       [ 0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
        -0.84452486, -0.17978084, -0.18569534]])

In [34]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [35]:
def evaluate(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mse)
    r2=r2_score(true,predicted)
    
    return mae,mse,rmse,r2

In [38]:
models={
    'Liner Regreesion':LinearRegression(),
    'Ridge Regression':Ridge(),
    'Lasso Regression':Lasso(),
    'Decisiontree Regression':DecisionTreeRegressor(),
    "KNN REgressor":KNeighborsRegressor(),
    "AdaBoost REgressor":AdaBoostRegressor(),
    "Random Forest REgressor":RandomForestRegressor(),
    "Gradient Regressor":GradientBoostingRegressor()
}


for i in range (len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    y_train_pred=model.predict(X_train)
    y_test_pred=model.predict(X_test)
    
    
    model_train_mae, model_train_mse ,model_train_rmse, model_train_r2 = evaluate(y_train,y_train_pred)
    
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2 = evaluate(y_test,y_test_pred)
    
    
    print(list(models.keys())[i])
    
    print("MOdel performance on training data->")
    
    print("-Mae :{:.4f}".format(model_train_mae))
    print("-Mse :{:.4f}".format(model_train_mse))
    print("-rmse :{:.4f}".format(model_train_rmse))
    print("-r2 :{:.4f}".format(model_train_r2))
    
    
    print("-"*30)
    
    print("Model Performance on test data")
    
    print("-Mae :{:.4f}".format(model_test_mae))
    print("-Mse :{:.4f}".format(model_test_mse))
    print("-rmse :{:.4f}".format(model_test_rmse))
    print("r2 :{:.4f}".format(model_test_r2))
    
    print("="*35)
    print("\n")

Liner Regreesion
MOdel performance on training data->
-Mae :1.9641
-Mse :14.1331
-rmse :3.7594
-r2 :0.8245
------------------------------
Model Performance on test data
-Mae :2.3982
-Mse :14.8705
-rmse :3.8562
r2 :0.7052
===================================


Ridge Regression
MOdel performance on training data->
-Mae :1.9512
-Mse :14.1388
-rmse :3.7602
-r2 :0.8244
------------------------------
Model Performance on test data
-Mae :2.3781
-Mse :14.6964
-rmse :3.8336
r2 :0.7086
===================================


Lasso Regression
MOdel performance on training data->
-Mae :2.0336
-Mse :16.8000
-rmse :4.0988
-r2 :0.7913
------------------------------
Model Performance on test data
-Mae :2.4868
-Mse :14.6624
-rmse :3.8291
r2 :0.7093
===================================


Decisiontree Regression
MOdel performance on training data->
-Mae :0.0000
-Mse :0.0000
-rmse :0.0000
-r2 :1.0000
------------------------------
Model Performance on test data
-Mae :1.5929
-Mse :8.7555
-rmse :2.9590
r2 :0.8264
===================================


KNN REgressor
MOdel performance on training data->
-Mae :1.4315
-Mse :15.1435
-rmse :3.8915
-r2 :0.8119
------------------------------
Model Performance on test data
-Mae :1.6553
-Mse :8.3535
-rmse :2.8902
r2 :0.8344
===================================


AdaBoost REgressor
MOdel performance on training data->
-Mae :1.7196
-Mse :5.0811
-rmse :2.2541
-r2 :0.9369
------------------------------
Model Performance on test data
-Mae :2.1974
-Mse :10.7308
-rmse :3.2758
r2 :0.7872
===================================


Random Forest REgressor
MOdel performance on training data->
-Mae :0.6131
-Mse :3.2812
-rmse :1.8114
-r2 :0.9592
------------------------------
Model Performance on test data
-Mae :1.8069
-Mse :9.9661
-rmse :3.1569
r2 :0.8024
===================================


Gradient Regressor
MOdel performance on training data->
-Mae :0.5545
-Mse :0.7185
-rmse :0.8476
-r2 :0.9911
------------------------------
Model Performance on test data
-Mae :1.6489
-Mse :7.9876
-rmse :2.8262
r2 :0.8416
===================================