Random forest Classifier is a machine learning algorithm wich uses multiple decision trees to make the 
prediction and selects the majority of the output predicted values

Many machine learning models works on only numerical data not text data , if the dataset contains city,marriage status,etc... it is in text form so we use onehot encoder to convert the textual classifier values to numerical boolean values , So that the model will be trained and tested on numerical data

If we are using any model , the dataset contains numerical values and the categorical values , so we scale the numerical vallues and encode the categorical values , So both have to do manually and join after doing them , the code looks messy , To overcome this difficulty we use ColumnTransformers , it would scale the numerical data and onehot the categorical data and combines them using a single variable . so it woould be easy to train and test the training and testing the data ...
Remember --> only use fit_transform on training data ad use transform on test data

## Holiday Package Prediciton

### 1) Problem statement.
"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base.
One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information.
The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being.
However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.
### 2) Data Collection.
The Dataset is collected from https://www.kaggle.com/datasets/susant4learning/holiday-package-purchase-prediction
The data consists of 20 column and 4888 rows.

### So this is the probelm Statement

### We train the data using multiple models

### Extract the data from Dataset and clean the dataset

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("travelling.csv")

In [3]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [4]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

## Data handling 
### Finding null data
### Filling the null data
### Replacing the duplicates
### Check datatype
### Understand the dataset

### Replacing the duplicates

In [5]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [6]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [7]:
df['Gender']=df['Gender'].replace('Fe Male','Female')

In [8]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [9]:
df['MaritalStatus']=df['MaritalStatus'].replace('Single','Unmarried')

In [10]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [11]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

#### np.round() function returns the decimal places of the particular value in here it returns with 5 decimal places of this particular variable

In [12]:
##Checking missing values

features_with_na=[features for features in df.columns if df[features].isnull().sum()>=1]

for i in features_with_na:
    print(i,np.round(df[i].isnull().mean() * 100,5)," % missing values")

Age 4.62357  % missing values
TypeofContact 0.51146  % missing values
DurationOfPitch 5.13502  % missing values
NumberOfFollowups 0.92062  % missing values
PreferredPropertyStar 0.53191  % missing values
NumberOfTrips 2.86416  % missing values
NumberOfChildrenVisiting 1.35025  % missing values
MonthlyIncome 4.76678  % missing values

In [13]:
#Statiscs on numerical data (Null col)
df[features_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [14]:
df[features_with_na]

,Age,TypeofContact,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
0,41.0,Self Enquiry,6.0,3.0,3.0,1.0,0.0,20993.0
1,49.0,Company Invited,14.0,4.0,4.0,2.0,2.0,20130.0
2,37.0,Self Enquiry,8.0,4.0,3.0,7.0,0.0,17090.0
3,33.0,Company Invited,9.0,3.0,3.0,2.0,1.0,17909.0
4,NaN,Self Enquiry,8.0,3.0,4.0,1.0,0.0,18468.0
...,...,...,...,...,...,...,...,...
4883,49.0,Self Enquiry,9.0,5.0,4.0,2.0,1.0,26576.0
4884,28.0,Company Invited,31.0,5.0,3.0,3.0,2.0,21212.0
4885,52.0,Self Enquiry,17.0,4.0,4.0,7.0,3.0,31820.0
4886,19.0,Self Enquiry,16.0,4.0,3.0,3.0,2.0,20289.0
4887,36.0,Self Enquiry,14.0,4.0,4.0,3.0,2.0,24041.0

## Imputing the null values
### Age with median
### Typeofcontact with mode
### Duration of pitch with median
### Numberoffollowups with mode
### Preferredpropertystar with mode
### NumberofTrips with median
### Numberofchildrevisiting with mode
### Monthly income with median

In [15]:
df.Age.fillna(df.Age.median(),inplace=True)
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [16]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [17]:
df.drop(columns='CustomerID',inplace=True,axis=1)

In [18]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [19]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'],inplace=True,axis=1)

In [20]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

## Feature Ectraction

Standardizing the numerical data and onehot encoding the categorical data

In [21]:
#Numerical Features
num_features=[features for features in df.columns if df[features].dtype != 'O']
print("No.of numerical columns is :",len(num_features))

No.of numerical columns is : 12

In [22]:
cat_features=[features for features in df.columns if df[features].dtype=='O']
print("no.of of categorical features is ", len(cat_features))

no.of of categorical features is  6

In [23]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [24]:
from sklearn.model_selection import train_test_split
X=df.drop(columns='ProdTaken',axis=1)
y=df['ProdTaken']

In [25]:
X.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [26]:
y

0       1
1       0
2       1
3       0
4       0
       ..
4883    1
4884    1
4885    1
4886    1
4887    1
Name: ProdTaken, Length: 4888, dtype: int64

In [27]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape,y_train.shape

((3421, 17), (3421,))

In [29]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4888 non-null   float64
 1   TypeofContact           4888 non-null   object
 2   CityTier                4888 non-null   int64
 3   DurationOfPitch         4888 non-null   float64
 4   Occupation              4888 non-null   object
 5   Gender                  4888 non-null   object
 6   NumberOfFollowups       4888 non-null   float64
 7   ProductPitched          4888 non-null   object
 8   PreferredPropertyStar   4888 non-null   float64
 9   MaritalStatus           4888 non-null   object
 10  NumberOfTrips           4888 non-null   float64
 11  Passport                4888 non-null   int64
 12  PitchSatisfactionScore  4888 non-null   int64
 13  OwnCar                  4888 non-null   int64
 14  Designation             4888 non-null   object
 15  MonthlyIncome           4888 non-null   float64
 16  TotalVisiting           4888 non-null   float64
dtypes: float64(7), int64(4), object(6)
memory usage: 649.3+ KB

In [30]:
cat_features=X.select_dtypes(include='object').columns
num_features=X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

num_scaler = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocesor= ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,cat_features),
        ('StandardScaler',num_scaler,num_features)
    ]
)

In [31]:
preprocesor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'Passport',
       'PitchSatisfactionScore', 'OwnCar', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [32]:
X_train.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
736,48.0,Self Enquiry,1,10.0,Salaried,Male,4.0,Standard,3.0,Unmarried,1.0,0,5,1,Senior Manager,25999.0,4.0
1615,30.0,Self Enquiry,1,11.0,Large Business,Female,3.0,Basic,5.0,Married,6.0,0,5,0,Executive,18204.0,3.0
336,29.0,Self Enquiry,1,14.0,Salaried,Male,5.0,Basic,5.0,Divorced,2.0,1,3,1,Executive,17119.0,4.0
4526,29.0,Self Enquiry,3,9.0,Small Business,Female,4.0,Deluxe,4.0,Married,3.0,1,3,1,Manager,23457.0,5.0
2665,34.0,Self Enquiry,1,11.0,Small Business,Female,5.0,Basic,4.0,Divorced,8.0,0,4,0,Executive,21300.0,4.0

In [33]:
X_train=preprocesor.fit_transform(X_train)

In [34]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,-0.714031,-0.649789,0.280718,-0.727208,-1.217370,-0.632714,1.409081,0.781435,0.460318,-0.067869
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.714031,-0.527737,-0.719632,1.768057,1.504605,-0.632714,1.409081,-1.279697,-1.005668,-0.777901
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.161582,1.281068,1.768057,-0.672975,1.580492,-0.046813,0.781435,-1.209722,-0.067869
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,-0.771841,0.280718,0.520424,-0.128580,1.580492,-0.046813,0.781435,-0.017750,0.642163
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.527737,1.281068,0.520424,2.593396,-0.632714,0.681134,-1.279697,-0.423411,-0.067869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.649789,1.281068,-0.727208,-0.672975,-0.632714,-1.502707,0.781435,-0.531926,0.642163
3417,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.470853,-0.893893,-0.719632,1.768057,-1.217370,-0.632714,1.409081,0.781435,1.512744,-0.067869
3418,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.470853,1.547143,0.280718,-0.727208,2.049001,-0.632714,-0.774760,0.781435,-0.357400,0.642163
3419,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,1.791246,1.281068,-0.727208,-0.128580,-0.632714,-1.502707,0.781435,-0.250765,0.642163
3420,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.771841,0.280718,-0.727208,-1.217370,1.580492,-0.046813,-1.279697,-1.071680,-1.487933

In [35]:
X_test=preprocesor.transform(X_test)

In [36]:
X_test

array([[ 0.        ,  0.        ,  0.        , ..., -1.27969734,
        -0.73033753, -0.777901  ],
       [ 1.        ,  0.        ,  0.        , ..., -1.27969734,
        -0.66394968, -0.06786916],
       [ 1.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.417017  , -0.777901  ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.78143477,
        -0.08075222, -0.06786916],
       [ 1.        ,  0.        ,  1.        , ...,  0.78143477,
         1.97576639, -0.06786916],
       [ 1.        ,  0.        ,  1.        , ..., -1.27969734,
         1.28837951, -1.48793284]], shape=(1467, 26))

In [37]:
y_train

736     0
1615    0
336     1
4526    0
2665    0
       ..
4426    0
466     0
3092    0
3772    0
860     1
Name: ProdTaken, Length: 3421, dtype: int64

In [38]:
y_train.value_counts()

ProdTaken
0    2775
1     646
Name: count, dtype: int64

### Random Forest Classifier
Training and testing on Different Models

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score,roc_auc_score

In [44]:

models={
    'Logistic Regression':LogisticRegression(),
    'DecisionTree Classifier':DecisionTreeClassifier(),
    'RandomForest Classifier':RandomForestClassifier(),
    'GradientBoost Classifier':GradientBoostingClassifier()
}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    #Make predictions
    y_pred_train=model.predict(X_train)
    y_pred_test=model.predict(X_test)
    
    
    #Training score
    model_train_accuracy=accuracy_score(y_train,y_pred_train)
    model_train_recall_score=recall_score(y_train,y_pred_train)
    model_train_f1_score=f1_score(y_train,y_pred_train , average='weighted')
    model_train_precision_score=precision_score(y_train,y_pred_train)
    model_train_roc_auc_score=roc_auc_score(y_train,y_pred_train)
    
    #Test score
    model_test_accuracy=accuracy_score(y_test,y_pred_test)
    model_test_recall_score=recall_score(y_test,y_pred_test)
    model_test_f1_score=f1_score(y_test,y_pred_test , average='weighted')
    model_test_precision_score=precision_score(y_test,y_pred_test)
    model_test_roc_auc_score=roc_auc_score(y_test,y_pred_test)
    
    
    print(list(models.keys())[i])
    
    print("Model performance on training data")
    
    print("-Accuracy :{:.4f}".format(model_train_accuracy))
    print("-recall_score :{:.4f}".format(model_train_recall_score))
    print("-f1_score :{:.4f}".format(model_train_f1_score))
    print("-Precision_score :{:.4f}".format(model_train_precision_score))
    print("-roc_auc_score :{:.4f}".format(model_train_roc_auc_score))
    
    
    print("------------------------------------------")
    
    print("Model performance on testing data")
    
    print("-Accuracy :{:.4f}".format(model_test_accuracy))
    print("-recall_score :{:.4f}".format(model_test_recall_score))
    print("-f1_score :{:.4f}".format(model_test_f1_score))
    print("-Precision_score :{:.4f}".format(model_test_precision_score))
    print("-roc_auc_score :{:.4f}".format(model_test_roc_auc_score))
    


    print("="*35)
    print("\n")

Logistic Regression
Model performance on training data
-Accuracy :0.8451
-recall_score :0.3034
-f1_score :0.8188
-Precision_score :0.7101
-roc_auc_score :0.6373
------------------------------------------
Model performance on testing data
-Accuracy :0.8432
-recall_score :0.3139
-f1_score :0.8193
-Precision_score :0.6719
-roc_auc_score :0.6393
===================================


DecisionTree Classifier
Model performance on training data
-Accuracy :1.0000
-recall_score :1.0000
-f1_score :1.0000
-Precision_score :1.0000
-roc_auc_score :1.0000
------------------------------------------
Model performance on testing data
-Accuracy :0.8978
-recall_score :0.7482
-f1_score :0.8986
-Precision_score :0.7168
-roc_auc_score :0.8401
===================================


RandomForest Classifier
Model performance on training data
-Accuracy :1.0000
-recall_score :1.0000
-f1_score :1.0000
-Precision_score :1.0000
-roc_auc_score :1.0000
------------------------------------------
Model performance on testing data
-Accuracy :0.9237
-recall_score :0.6350
-f1_score :0.9177
-Precision_score :0.9355
-roc_auc_score :0.8125
===================================


GradientBoost Classifier
Model performance on training data
-Accuracy :0.8948
-recall_score :0.5124
-f1_score :0.8833
-Precision_score :0.8803
-roc_auc_score :0.7481
------------------------------------------
Model performance on testing data
-Accuracy :0.8766
-recall_score :0.4562
-f1_score :0.8628
-Precision_score :0.7962
-roc_auc_score :0.7147
===================================

### For only RandomForest Classifier Hyper Parameter Tuning
It could give you better recall Score

In [45]:
models={
    "Random Forest ":RandomForestClassifier(n_estimators=1000,max_depth=None,min_samples_split=2,
                                            max_features=7)
}


for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    
    #Make predictions
    y_pred_train=model.predict(X_train)
    y_pred_test=model.predict(X_test)
    
    
    #Training score
    model_train_accuracy=accuracy_score(y_train,y_pred_train)
    model_train_recall_score=recall_score(y_train,y_pred_train)
    model_train_f1_score=f1_score(y_train,y_pred_train , average='weighted')
    model_train_precision_score=precision_score(y_train,y_pred_train)
    model_train_roc_auc_score=roc_auc_score(y_train,y_pred_train)
    
    #Test score
    model_test_accuracy=accuracy_score(y_test,y_pred_test)
    model_test_recall_score=recall_score(y_test,y_pred_test)
    model_test_f1_score=f1_score(y_test,y_pred_test , average='weighted')
    model_test_precision_score=precision_score(y_test,y_pred_test)
    model_test_roc_auc_score=roc_auc_score(y_test,y_pred_test)
    
    
    print(list(models.keys())[i])
    
    print("Model performance on training data")
    
    print("-Accuracy :{:.4f}".format(model_train_accuracy))
    print("-recall_score :{:.4f}".format(model_train_recall_score))
    print("-f1_score :{:.4f}".format(model_train_f1_score))
    print("-Precision_score :{:.4f}".format(model_train_precision_score))
    print("-roc_auc_score :{:.4f}".format(model_train_roc_auc_score))
    
    
    print("------------------------------------------")
    
    print("Model performance on testing data")
    
    print("-Accuracy :{:.4f}".format(model_test_accuracy))
    print("-recall_score :{:.4f}".format(model_test_recall_score))
    print("-f1_score :{:.4f}".format(model_test_f1_score))
    print("-Precision_score :{:.4f}".format(model_test_precision_score))
    print("-roc_auc_score :{:.4f}".format(model_test_roc_auc_score))
    


    print("="*35)
    print("\n")

Random Forest
Model performance on training data
-Accuracy :1.0000
-recall_score :1.0000
-f1_score :1.0000
-Precision_score :1.0000
-roc_auc_score :1.0000
------------------------------------------
Model performance on testing data
-Accuracy :0.9250
-recall_score :0.6460
-f1_score :0.9195
-Precision_score :0.9316
-roc_auc_score :0.8175
===================================