In [104]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [102]:
df=pd.read_csv("economics.csv")

In [103]:
df

    year  month  interest_rate  unemployment_rate  index_price
0   2017     12           2.75                5.3         1464
1   2017     11           2.50                5.3         1394
2   2017     10           2.50                5.3         1357
3   2017      9           2.50                5.3         1293
4   2017      8           2.50                5.4         1256
5   2017      7           2.50                5.6         1254
6   2017      6           2.50                5.5         1234
7   2017      5           2.25                5.5         1195
8   2017      4           2.25                5.5         1159
9   2017      3           2.25                5.6         1167
10  2017      2           2.00                5.7         1130
11  2017      1           2.00                5.9         1075
12  2016     12           2.00                6.0         1047
13  2016     11           1.75                5.9          965
14  2016     10           1.75                5.8          943
15  2016      9           1.75                6.1          958
16  2016      8           1.75                6.2          971
17  2016      7           1.75                6.1          949
18  2016      6           1.75                6.1          884
19  2016      5           1.75                6.1          866
20  2016      4           1.75                5.9          876
21  2016      3           1.75                6.2          822
22  2016      2           1.75                6.2          704
23  2016      1           1.75                6.1          719

In [105]:
df.drop(columns=['year','month'],axis=1,inplace=True)

In [106]:
df

    interest_rate  unemployment_rate  index_price
0            2.75                5.3         1464
1            2.50                5.3         1394
2            2.50                5.3         1357
3            2.50                5.3         1293
4            2.50                5.4         1256
5            2.50                5.6         1254
6            2.50                5.5         1234
7            2.25                5.5         1195
8            2.25                5.5         1159
9            2.25                5.6         1167
10           2.00                5.7         1130
11           2.00                5.9         1075
12           2.00                6.0         1047
13           1.75                5.9          965
14           1.75                5.8          943
15           1.75                6.1          958
16           1.75                6.2          971
17           1.75                6.1          949
18           1.75                6.1          884
19           1.75                6.1          866
20           1.75                5.9          876
21           1.75                6.2          822
22           1.75                6.2          704
23           1.75                6.1          719

In [107]:
df.head()

   interest_rate  unemployment_rate  index_price
0           2.75                5.3         1464
1           2.50                5.3         1394
2           2.50                5.3         1357
3           2.50                5.3         1293
4           2.50                5.4         1256

In [109]:
x=df.iloc[:,:-1]
y=df.iloc[:, -1]

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)


model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("Coefficient:",model.coef_)
print("intercept:",model.intercept_)

Coefficient: [ 260.33709119 -360.58377051]
intercept: 2601.67998660565

In [112]:
new_data=[[2,6]]        #interest rate,unemployement rate
i_price=model.predict(new_data)

print(i_price)

[958.85154593]

/home/bhargav/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [115]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

print("MSE:",mean_squared_error(y_test,y_pred))
print("MAE:",mean_absolute_error(y_test,y_pred))
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
print("r-mse:",rmse)

MSE: 5793.762887712554
MAE: 59.935781523235505
r-mse: 76.11677139574796