### Bow and Tf-idf machine learning algorithms or techniques
In general Machine Computers do not understands the direct sentences , so the sentences must convert into numerical values .
So we use the techniques called Bag of words and term Frequeny - invert document frequency 
Each has differrent approaches 
1)Bag of Words
It uses the vocabulary(unique words)
and then calculates the value for the words , It gives equal priority to every word

2)Term Frequency and Invert Document Frequency
It gives high priority to the important words
It often measures how many times a word appeared in the sentece
and applies a logarithmic Formula

### Word2Vec 
    -> It is also a nlp technique to convert words to vectors 
    -> It was published by the google 
    -> The model trains over a 3 billion words
    -> The words are converted in to vectors , intially the model assigns random values to the words , each word represented as the 
    -> 300 dimensional vector and lastly averages the vector values into a single vector of 300 dimension

### Basic Workflow of a machine learning algorithm
    ->Preprocessing and Cleaning
    ->Train and Test split
    ->BOW and TF-IDF (Sentences --> Vectors)
    ->ML Models To train the data

### Re Module
re stands for Regular Expressions is a Module in python is used in searching ,matching , replacing , and manipulating the text patterns
-> To keep only alphabets in the dataset 
        -> use text='i love! python, programming language'
        -> clean_text=re.sub(r'[^a-zA-Z ]','',text)
    -> re.sub(pattern,replacement,string)

### Split function returns a list of words from a text
    text=text.split() -> default method to separate the text based on the space
    text=text.split(',') -> separate based on the comma

### Difference betweeen the fit_transform and Transform
    fit-> learns patterns from the data like a relationship 
    transform-> applies that pattern to the data
So we use the fit_transform on the train data to learn a relationship
and apply the transform on the test data on unseen data like applying a same relationship on the unseen data

### Cosine similarity 
        -> It is a measure used to determine how similar two vectors are
        -> It tells is the two values related or not
        -> it ranges from -1 0 1

In [126]:
import pandas as pd
df=pd.read_csv("SMSSpamCollection",sep='\t',names=['label','message'])

In [127]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [128]:
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

### Make a Small dataset from the big dataset
df.sample --> used random samples
df.head(150) --> used first 150 samples

In [129]:
df_small=df.sample(n=150,random_state=42)
df_small=df_small.reset_index(drop=True)

In [130]:
df_small.head()

  label                                            message
0   ham  Squeeeeeze!! This is christmas hug.. If u lik ...
1   ham  And also I've sorta blown him off a couple tim...
2   ham  Mmm thats better now i got a roast down me! i...
3   ham      Mm have some kanji dont eat anything heavy ok
4   ham  So there's a ring that comes with the guys cos...

In [131]:
df_small

    label                                            message
0     ham  Squeeeeeze!! This is christmas hug.. If u lik ...
1     ham  And also I've sorta blown him off a couple tim...
2     ham  Mmm thats better now i got a roast down me! i...
3     ham      Mm have some kanji dont eat anything heavy ok
4     ham  So there's a ring that comes with the guys cos...
..    ...                                                ...
145   ham  You might want to pull out more just in case a...
146  spam  PRIVATE! Your 2004 Account Statement for 07849...
147   ham                                :-( sad puppy noise
148   ham    4 oclock at mine. Just to bash out a flat plan.
149   ham  We not watching movie already. Xy wants 2 shop...

[150 rows x 2 columns]

In [132]:
df_small['label'].value_counts()

label
ham     133
spam     17
Name: count, dtype: int64

In [133]:
df_small.shape

(150, 2)

In [134]:
df_small['message']

0      Squeeeeeze!! This is christmas hug.. If u lik ...
1      And also I've sorta blown him off a couple tim...
2      Mmm thats better now i got a roast down me! i...
3          Mm have some kanji dont eat anything heavy ok
4      So there's a ring that comes with the guys cos...
                             ...
145    You might want to pull out more just in case a...
146    PRIVATE! Your 2004 Account Statement for 07849...
147                                  :-( sad puppy noise
148      4 oclock at mine. Just to bash out a flat plan.
149    We not watching movie already. Xy wants 2 shop...
Name: message, Length: 150, dtype: object

In [135]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
lemmatizer=WordNetLemmatizer()
import re

In [136]:
corpus=[]
for i in range (0,len(df_small)):
    review=re.sub('[^a-zA-Z]',' ',df_small['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [137]:
corpus

['squeeeeeze christmas hug u lik frndshp den hug back u get u r cute u r luvd u r lucky none people hate u',
 'also sorta blown couple time recently id rather text blue looking weed',
 'mmm thats better got roast b better drink good indian',
 'mm kanji dont eat anything heavy ok',
 'ring come guy costume gift future yowifes hint hint',
 'sary need tim bollox hurt lot tol',
 'love decision feeling could decide love life would much simpler less magical',
 'supervisor find one lor thk student havent ask yet tell u aft ask',
 'dear good morning',
 'chennai velachery',
 'lol grr mom taking forever prescription pharmacy like minute away ugh',
 'valentine huh proof fb page ugh glad really watch rupaul show tool',
 'wif buying tix lar',
 'er hello thing quite go plan limping slowly home followed aa exhaust hanging',
 'free ringtone text first poly text get true tone help st free tone x pw e nd txt stop',
 'sir waiting call',
 'crazy ar married like gd looking guy frens like say korean leona fave dun thk aft thinking mayb prob go',
 'hey free call',
 'fighting world easy u either win lose bt fightng close u dificult u lose u lose u win u still lose',
 'u go back urself lor',
 'yeah leave couple minute amp let know get mu',
 'customer place call',
 'err cud going pm got way contact',
 'guess worried must know way body repair quite sure worry take slow first test guide ovulation relax nothing said reason worry keep followin',
 'nd time tried contact u u pound prize claim easy call p per minute bt national rate',
 'k k congratulation',
 'still looking job much ta earn',
 'gud gud k chikku tke care sleep well gud nyt',
 'give time walk',
 'wat',
 'nothing u dinner w u',
 'thanx yup coming back sun finish dinner going back hotel time fly tog exactly mth today hope haf many mths come',
 'xy going e lunch',
 'pls send company name saibaba colany',
 'ur change da report big co already made change da previous report',
 'morning ok',
 'yeah jus rite',
 'never lei v lazy got wat dat day send da url cant work one',
 'aight head',
 'prefer free day tues wed fri oso ask workin lor',
 'reminder downloaded content already paid goto http doit mymoby tv collect content',
 'jus finish blowing hair u finish dinner already',
 'pay like lt gt yr difficult',
 'hello boytoy geeee missing today like send tm remind thinking loved loving kiss',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'anything lor',
 'text creepy like think forgot',
 'guess somebody know secretly fancy wanna find give u call landline datebox essexcm xn p min',
 'like jerk',
 'office whats matter msg call break',
 'best watch say cause get drunk motherfucker',
 'free st week nokia tone ur mob every week txt nokia get txting tell ur mate www getzed co uk pobox w wq norm p tone',
 'hey da cool iknow wellda peril studentfinancial crisis spk u l r',
 'nah help never iphone',
 'ok',
 'even friend priest call',
 'oh gei happend tron maybe ill dl',
 'seeing missed call dear brother gr day',
 'free day finish mon n thurs',
 'good evening sir hope nice day wanted bring notice late paying rent past month pay lt gt charge felt would inconsiderate nag something give great cost didnt speak however recession wont able pay charge month hence askin well ahead month end please help thank everything',
 'urgent mobile number awarded prize guaranteed call land line claim valid hr ppm',
 'wat time r going xin hostel',
 'message free welcome new improved sex dogging club unsubscribe service reply stop msg p',
 'hi hope u get txt journey hasnt gd min late think',
 'bill letter expecting one orange bill may still say orange',
 'annoying',
 'went project centre',
 'roger probably going rem',
 'lol know awesome phone could click delete right want',
 'height oh shit situation guy throw luv letter gal fall brother head who gay',
 'sm service inclusive text credit pls goto www comuk net login qxj unsubscribe stop extra charge help comuk cm ae',
 'made day great day',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'today voda number ending selected receive award hava match please call quoting claim code standard rate app',
 'oh god found number glad text back xafter msg cst std ntwk chg',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'still around looking pick later',
 'neft transaction reference number lt gt r lt decimal gt credited beneficiary account lt gt lt time gt lt gt',
 'ok take ur time n enjoy ur dinner',
 'hey cutie go wale kinda ok like hill shit still avent killed',
 'thanks loving rock',
 'reached already',
 'home',
 'also piece',
 'next amazing xxx picsfree video sent enjoy one vid enough day text back keyword picsfree get next video',
 'quite ok bit ex u better go eat smth else feel guilty',
 'dude got haircut breezy',
 'actually fuck whatever find excuse tampa point january though',
 'management puzzeles',
 'hey whats plan sat',
 'fear fainting housework quick cuppa',
 'oh ho first time u use type word',
 'aiyar u poor thing give u support k jia think u',
 'got fujitsu ibm hp toshiba got lot model say',
 'prepare pounded every night',
 'yeah like go like friend imma flip shit like half hour',
 'wow healthy old airport rd lor cant thk anything else b bathing dog later',
 'dai lt gt naal eruku',
 'ask around lot term mids',
 'u reckon need arrange transport u thanks',
 'yes fine',
 'wait inside da car park',
 'dear got train seat mine lower seat',
 'th gower mate r u man good wale ill b back morrow c u wk msg random',
 'edison rightly said fool ask question wise man answer know u speechless viva gm gn ge gnt',
 'r u still working',
 'yeah sure thing mate haunt got stuff sorted im going sound anyway promoting hex way dont know number joke',
 'amazing quote sometimes life difficult decide whats wrong lie brings smile truth brings tear',
 'ok ok ok whats ur today plan',
 'sleeping nt feeling well',
 'hiya comin bristol st week april le got rudi new yr eve snoring drunk u bak college yet work sends ink bath',
 'going write ccna exam week',
 'well might come',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'height confidence aeronautics professor wer calld amp wer askd sit aeroplane aftr sat wer told dat plane w made student dey hurried plane bt didnt move said made student wont even start datz confidence',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'oh half hour much longer syria canada eh wow must get much work done day u extra time grin',
 'lmao take pic send',
 'rock yr chik get filthy film xxx pic yr phone rply filth saristar ltd e yt p per day stop cancel',
 'watching live',
 'sir need velusamy sir date birth company bank facility detail',
 'anything lar',
 'cool text head',
 'know thinkin malaria relax child cant handle malaria would worse gastroenteritis take enough replace loss temp reduce give malaria med vomit self limiting illness mean day completely stop',
 'yo chad gymnastics class wanna take site say christian class full',
 'sure get acknowledgement astoundingly tactless generally faggy demand blood oath fo',
 'hi test lt gt rd',
 'house maid murderer coz man murdered lt gt th january public holiday govt instituitions closed including post office',
 'sm auction brand new nokia auction today auction free join take part txt nokia',
 'yeah usual guy town definitely people around know',
 'babe miiiiiiissssssssss need crave geeee sad without babe love',
 'happy new year man',
 'hey thk juz go accordin wat discussed yest lor except kb sun co nt much lesson go attend kb sat',
 'taking half day leave bec well',
 'maybe fat finger press button know',
 'babe go day miss already love loving kiss hope everything go well',
 'black shirt n blue jean thk c',
 'gudnite tc practice going',
 'worry hope photo shoot went well spiffing fun workage',
 'nt driving even many reason called bbd thts chikku hw abt dvg cold heard tht vinobanagar violence hw condition hw ru problem',
 'mom want know',
 'good good job like entrepreneur',
 'got tv watch meh u work today',
 'pls pls send mail know relative coming deliver know cost risk benefit anything else thanks',
 'might want pull case plan spending much confidence derek taylor money management',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'sad puppy noise',
 'oclock mine bash flat plan',
 'watching movie already xy want shop shopping w']

In [138]:
### Extract Output feature
y=pd.get_dummies(df_small['label'])

In [139]:
y

       ham   spam
0     True  False
1     True  False
2     True  False
3     True  False
4     True  False
..     ...    ...
145   True  False
146  False   True
147   True  False
148   True  False
149   True  False

[150 rows x 2 columns]

In [140]:
y=y.iloc[:,0].values

In [141]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True])

In [142]:
type(corpus),type(y)

(list, numpy.ndarray)

In [143]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [144]:
len(X_train),len(y_train)

(120, 120)

In [145]:
len(X_test),len(y_test)

(30, 30)

In [146]:
### For small dataset we don't use the max_feature parameter
#Bag of words
from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(ngram_range=(1,2))

In [147]:
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [148]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(120, 1598))

In [149]:
cv.vocabulary_

{'maybe': 844,
 'fat': 427,
 'finger': 452,
 'press': 1064,
 'button': 161,
 'know': 723,
 'maybe fat': 845,
 'fat finger': 428,
 'finger press': 453,
 'press button': 1065,
 'button know': 162,
 'aiyar': 30,
 'poor': 1051,
 'thing': 1359,
 'give': 509,
 'support': 1309,
 'jia': 695,
 'think': 1364,
 'aiyar poor': 31,
 'poor thing': 1052,
 'thing give': 1360,
 'give support': 512,
 'support jia': 1310,
 'jia think': 696,
 'even': 398,
 'friend': 479,
 'priest': 1068,
 'call': 165,
 'even friend': 399,
 'friend priest': 480,
 'priest call': 1069,
 'gudnite': 576,
 'tc': 1332,
 'practice': 1058,
 'going': 533,
 'gudnite tc': 577,
 'tc practice': 1333,
 'practice going': 1059,
 'pls': 1043,
 'send': 1201,
 'mail': 819,
 'relative': 1136,
 'coming': 245,
 'deliver': 324,
 'cost': 264,
 'risk': 1160,
 'benefit': 108,
 'anything': 48,
 'else': 376,
 'thanks': 1351,
 'pls pls': 1044,
 'pls send': 1045,
 'send mail': 1202,
 'mail know': 820,
 'know relative': 727,
 'relative coming': 1137,
 'coming deliver': 247,
 'deliver know': 325,
 'know cost': 724,
 'cost risk': 266,
 'risk benefit': 1161,
 'benefit anything': 109,
 'anything else': 49,
 'else thanks': 379,
 'prepare': 1062,
 'pounded': 1055,
 'every': 404,
 'night': 943,
 'prepare pounded': 1063,
 'pounded every': 1056,
 'every night': 405,
 'babe': 83,
 'miiiiiiissssssssss': 856,
 'need': 923,
 'crave': 272,
 'geeee': 495,
 'sad': 1175,
 'without': 1541,
 'love': 790,
 'babe miiiiiiissssssssss': 86,
 'miiiiiiissssssssss need': 857,
 'need crave': 925,
 'crave geeee': 273,
 'geeee sad': 497,
 'sad without': 1177,
 'without babe': 1542,
 'babe love': 85,
 'dear': 308,
 'shall': 1211,
 'tonite': 1406,
 'busy': 159,
 'street': 1293,
 'update': 1436,
 'looking': 772,
 'ok': 976,
 'varunnathu': 1461,
 'edukkukayee': 372,
 'raksha': 1102,
 'ollu': 985,
 'good': 540,
 'one': 987,
 'real': 1113,
 'sense': 1204,
 'dear shall': 312,
 'shall mail': 1212,
 'mail tonite': 821,
 'tonite busy': 1407,
 'busy street': 160,
 'street shall': 1294,
 'shall update': 1213,
 'update tonite': 1439,
 'tonite thing': 1408,
 'thing looking': 1361,
 'looking ok': 774,
 'ok varunnathu': 981,
 'varunnathu edukkukayee': 1462,
 'edukkukayee raksha': 373,
 'raksha ollu': 1103,
 'ollu good': 986,
 'good one': 546,
 'one real': 990,
 'real sense': 1114,
 'nd': 921,
 'time': 1382,
 'tried': 1419,
 'contact': 257,
 'pound': 1053,
 'prize': 1072,
 'claim': 218,
 'easy': 364,
 'per': 1014,
 'minute': 863,
 'bt': 155,
 'national': 919,
 'rate': 1105,
 'nd time': 922,
 'time tried': 1387,
 'tried contact': 1420,
 'contact pound': 258,
 'pound prize': 1054,
 'prize claim': 1073,
 'claim easy': 221,
 'easy call': 365,
 'call per': 173,
 'per minute': 1016,
 'minute bt': 865,
 'bt national': 158,
 'national rate': 920,
 'message': 851,
 'free': 474,
 'welcome': 1507,
 'new': 934,
 'improved': 681,
 'sex': 1209,
 'dogging': 346,
 'club': 229,
 'unsubscribe': 1434,
 'service': 1207,
 'reply': 1152,
 'stop': 1288,
 'msg': 897,
 'message free': 852,
 'free welcome': 478,
 'welcome new': 1508,
 'new improved': 935,
 'improved sex': 682,
 'sex dogging': 1210,
 'dogging club': 347,
 'club unsubscribe': 230,
 'unsubscribe service': 1435,
 'service reply': 1208,
 'reply stop': 1153,
 'stop msg': 1290,
 'oh': 972,
 'god': 531,
 'found': 472,
 'number': 957,
 'glad': 514,
 'text': 1342,
 'back': 87,
 'xafter': 1570,
 'cst': 280,
 'std': 1279,
 'ntwk': 955,
 'chg': 208,
 'oh god': 974,
 'god found': 532,
 'found number': 473,
 'number glad': 960,
 'glad text': 516,
 'text back': 1343,
 'back xafter': 93,
 'xafter msg': 1571,
 'msg cst': 899,
 'cst std': 281,
 'std ntwk': 1280,
 'ntwk chg': 956,
 'watching': 1499,
 'live': 769,
 'watching live': 1500,
 'ur': 1442,
 'change': 201,
 'da': 289,
 'report': 1154,
 'big': 116,
 'co': 231,
 'already': 32,
 'made': 814,
 'previous': 1066,
 'ur change': 1443,
 'change da': 202,
 'da report': 293,
 'report big': 1155,
 'big co': 117,
 'co already': 232,
 'already made': 34,
 'made change': 815,
 'da previous': 292,
 'previous report': 1067,
 'december': 313,
 'mobile': 876,
 'mths': 903,
 'entitled': 391,
 'latest': 740,
 'colour': 242,
 'camera': 179,
 'december mobile': 314,
 'mobile mths': 879,
 'mths entitled': 905,
 'entitled update': 392,
 'update latest': 1438,
 'latest colour': 741,
 'colour camera': 243,
 'camera mobile': 180,
 'mobile free': 878,
 'free call': 475,
 'call mobile': 171,
 'mobile update': 881,
 'update co': 1437,
 'co free': 233,
 'bill': 118,
 'letter': 749,
 'expecting': 418,
 'orange': 992,
 'may': 841,
 'still': 1281,
 'say': 1188,
 'bill letter': 119,
 'letter expecting': 750,
 'expecting one': 419,
 'one orange': 989,
 'orange bill': 993,
 'bill may': 120,
 'may still': 843,
 'still say': 1286,
 'say orange': 1191,
 'cool': 261,
 'head': 609,
 'cool text': 263,
 'text head': 1346,
 'taking': 1326,
 'half': 592,
 'day': 300,
 'leave': 742,
 'bec': 104,
 'well': 1509,
 'taking half': 1327,
 'half day': 593,
 'day leave': 303,
 'leave bec': 743,
 'bec well': 105,
 'neft': 928,
 'transaction': 1414,
 'reference': 1132,
 'lt': 803,
 'gt': 562,
 'decimal': 318,
 'credited': 274,
 'beneficiary': 106,
 'account': 6,
 'neft transaction': 929,
 'transaction reference': 1416,
 'reference number': 1133,
 'number lt': 962,
 'lt gt': 805,
 'gt lt': 566,
 'lt decimal': 804,
 'decimal gt': 319,
 'gt credited': 564,
 'credited beneficiary': 275,
 'beneficiary account': 107,
 'account lt': 8,
 'lt time': 806,
 'time gt': 1385,
 'jus': 705,
 'finish': 454,
 'blowing': 129,
 'hair': 590,
 'dinner': 340,
 'jus finish': 706,
 'finish blowing': 455,
 'blowing hair': 130,
 'hair finish': 591,
 'finish dinner': 456,
 'dinner already': 341,
 'gei': 498,
 'happend': 597,
 'tron': 1421,
 'ill': 674,
 'dl': 343,
 'oh gei': 973,
 'gei happend': 499,
 'happend tron': 598,
 'tron maybe': 1422,
 'maybe ill': 846,
 'ill dl': 676,
 'height': 617,
 'shit': 1216,
 'situation': 1237,
 'guy': 583,
 'throw': 1374,
 'luv': 812,
 'gal': 486,
 'fall': 425,
 'brother': 152,
 'who': 1530,
 'gay': 490,
 'height oh': 619,
 'oh shit': 975,
 'shit situation': 1217,
 'situation guy': 1238,
 'guy throw': 584,
 'throw luv': 1375,
 'luv letter': 813,
 'letter gal': 751,
 'gal fall': 487,
 'fall brother': 426,
 'brother head': 154,
 'head who': 610,
 'who gay': 1531,
 'might': 853,
 'want': 1490,
 'pull': 1087,
 'case': 192,
 'plan': 1033,
 'spending': 1268,
 'much': 907,
 'confidence': 254,
 'derek': 328,
 'taylor': 1330,
 'money': 884,
 'management': 829,
 'might want': 855,
 'want pull': 1492,
 'pull case': 1088,
 'case plan': 193,
 'plan spending': 1036,
 'spending much': 1269,
 'much confidence': 908,
 'confidence derek': 256,
 'derek taylor': 329,
 'taylor money': 1331,
 'money management': 885,
 'roger': 1167,
 'probably': 1076,
 'rem': 1141,
 'roger probably': 1168,
 'probably going': 1077,
 'going rem': 537,
 'happy': 599,
 'year': 1582,
 'man': 826,
 'happy new': 600,
 'new year': 937,
 'year man': 1583,
 'hi': 635,
 'hope': 642,
 'get': 502,
 'txt': 1427,
 'journey': 703,
 'hasnt': 601,
 'gd': 491,
 'min': 858,
 'late': 736,
 'hi hope': 636,
 'hope get': 644,
 'get txt': 508,
 'txt journey': 1428,
 'journey hasnt': 704,
 'hasnt gd': 602,
 'gd min': 492,
 'min late': 859,
 'late think': 738,
 'urgent': 1448,
 'awarded': 81,
 'guaranteed': 570,
 'land': 733,
 'line': 767,
 'valid': 1456,
 'hr': 653,
 'ppm': 1057,
 'urgent mobile': 1449,
 'mobile number': 880,
 'number awarded': 958,
 'awarded prize': 82,
 'prize guaranteed': 1074,
 'guaranteed call': 571,
 'call land': 170,
 'land line': 734,
 'line claim': 768,
 'claim valid': 223,
 'valid hr': 1458,
 'hr ppm': 654,
 'rock': 1165,
 'yr': 1590,
 'chik': 209,
 'filthy': 446,
 'film': 442,
 'xxx': 1572,
 'pic': 1024,
 'phone': 1019,
 'rply': 1169,
 'filth': 444,
 'saristar': 1182,
 'ltd': 807,
 'yt': 1594,
 'cancel': 182,
 'rock yr': 1166,
 'yr chik': 1591,
 'chik get': 210,
 'get filthy': 505,
 'filthy film': 447,
 'film xxx': 443,
 'xxx pic': 1573,
 'pic yr': 1026,
 'yr phone': 1593,
 'phone rply': 1020,
 'rply filth': 1170,
 'filth saristar': 445,
 'saristar ltd': 1183,
 'ltd yt': 808,
 'yt per': 1595,
 'per day': 1015,
 'day stop': 305,
 'stop cancel': 1289,
 'creepy': 276,
 'like': 757,
 'forgot': 471,
 'text creepy': 1345,
 'creepy like': 277,
 'like think': 762,
 'think forgot': 1365,
 'reached': 1111,
 'reached already': 1112,
 'yeah': 1577,
 'rite': 1162,
 'yeah jus': 1578,
 'jus rite': 707,
 'evening': 402,
 'sir': 1228,
 'nice': 941,
 'wanted': 1493,
 'bring': 147,
 'notice': 950,
 'paying': 1010,
 'rent': 1146,
 'past': 1003,
 'month': 886,
 'pay': 1005,
 'charge': 203,
 'felt': 436,
 'would': 1560,
 'inconsiderate': 683,
 'nag': 915,
 'something': 1254,
 'great': 559,
 'didnt': 333,
 'speak': 1264,
 'however': 651,
 'recession': 1126,
 'wont': 1545,
 'able': 2,
 'hence': 626,
 'askin': 69,
 'ahead': 24,
 'end': 380,
 'please': 1040,
 'help': 623,
 'thank': 1349,
 'everything': 406,
 'good evening': 541,
 'evening sir': 403,
 'sir hope': 1230,
 'hope nice': 646,
 'nice day': 942,
 'day wanted': 307,
 'wanted bring': 1494,
 'bring notice': 148,
 'notice late': 951,
 'late paying': 737,
 'paying rent': 1011,
 'rent past': 1147,
 'past month': 1004,
 'month pay': 889,
 'pay lt': 1009,
 'gt charge': 563,
 'charge felt': 204,
 'felt would': 437,
 'would inconsiderate': 1561,
 'inconsiderate nag': 684,
 'nag something': 916,
 'something give': 1255,
 'give great': 510,
 'great cost': 560,
 'cost didnt': 265,
 'didnt speak': 335,
 'speak however': 1265,
 'however recession': 652,
 'recession wont': 1127,
 'wont able': 1546,
 'able pay': 3,
 'pay charge': 1006,
 'charge month': 205,
 'month hence': 888,
 'hence askin': 627,
 'askin well': 70,
 'well ahead': 1510,
 'ahead month': 25,
 'month end': 887,
 'end please': 381,
 'please help': 1042,
 'help thank': 625,
 'thank everything': 1350,
 'sure': 1311,
 'mate': 836,
 'haunt': 603,
 'got': 548,
 'stuff': 1301,
 'sorted': 1260,
 'im': 679,
 'sound': 1262,
 'anyway': 53,
 'promoting': 1083,
 'hex': 628,
 'way': 1501,
 'dont': 350,
 'joke': 702,
 'yeah sure': 1580,
 'sure thing': 1313,
 'thing mate': 1362,
 'mate haunt': 837,
 'haunt got': 604,
 'got stuff': 550,
 'stuff sorted': 1302,
 'sorted im': 1261,
 'im going': 680,
 'going sound': 538,
 'sound anyway': 1263,
 'anyway promoting': 54,
 'promoting hex': 1084,
 'hex way': 629,
 'way dont': 1504,
 'dont know': 352,
 'know number': 726,
 'number joke': 961,
 'wow': 1564,
 'healthy': 611,
 'old': 983,
 'airport': 28,
 'rd': 1109,
 'lor': 777,
 'cant': 183,
 'thk': 1370,
 'bathing': 100,
 'dog': 344,
 'later': 739,
 'wow healthy': 1565,
 'healthy old': 612,
 'old airport': 984,
 'airport rd': 29,
 'rd lor': 1110,
 'lor cant': 779,
 'cant thk': 185,
 'thk anything': 1371,
 'else bathing': 377,
 'bathing dog': 101,
 'dog later': 345,
 'fighting': 438,
 'world': 1550,
 'either': 374,
 'win': 1534,
 'lose': 782,
 'fightng': 440,
 'close': 227,
 'dificult': 338,
 'fighting world': 439,
 'world easy': 1551,
 'easy either': 366,
 'either win': 375,
 'win lose': 1535,
 'lose bt': 783,
 'bt fightng': 157,
 'fightng close': 441,
 'close dificult': 228,
 'dificult lose': 339,
 'lose lose': 784,
 'lose win': 785,
 'win still': 1536,
 'still lose': 1285,
 'take': 1319,
 'enjoy': 385,
 'ok take': 980,
 'take ur': 1325,
 'ur time': 1446,
 'time enjoy': 1383,
 'enjoy ur': 387,
 'ur dinner': 1444,
 'actually': 13,
 'fuck': 481,
 'whatever': 1523,
 'find': 448,
 'excuse': 414,
 'tampa': 1328,
 'point': 1048,
 'january': 691,
 'though': 1373,
 'actually fuck': 14,
 'fuck whatever': 482,
 'whatever find': 1524,
 'find excuse': 449,
 'excuse tampa': 415,
 'tampa point': 1329,
 'point january': 1050,
 'january though': 692,
 'couple': 269,
 'amp': 42,
 'let': 747,
 'mu': 906,
 'yeah leave': 1579,
 'leave couple': 744,
 'couple minute': 270,
 'minute amp': 864,
 'amp let': 43,
 'let know': 748,
 'know get': 725,
 'get mu': 506,
 'difficult': 336,
 'pay like': 1008,
 'like lt': 760,
 'gt yr': 569,
 'yr difficult': 1592,
 'lmao': 770,
 'lmao take': 771,
 'take pic': 1322,
 'pic send': 1025,
 'puzzeles': 1091,
 'management puzzeles': 830,
 'walk': 1487,
 'give time': 513,
 'time walk': 1388,
 'job': 697,
 'entrepreneur': 393,
 'good good': 542,
 'good job': 544,
 'job like': 698,
 'like entrepreneur': 758,
 'reminder': 1144,
 'downloaded': 353,
 'content': 259,
 'paid': 998,
 'goto': 553,
 'http': 655,
 'doit': 348,
 'mymoby': 913,
 'tv': 1425,
 'collect': 240,
 'reminder downloaded': 1145,
 'downloaded content': 354,
 'content already': 260,
 'already paid': 35,
 'paid goto': 999,
 'goto http': 554,
 'http doit': 656,
 'doit mymoby': 349,
 'mymoby tv': 914,
 'tv collect': 1426,
 'collect content': 241,
 'sm': 1247,
 'auction': 73,
 'brand': 144,
 'nokia': 945,
 'today': 1395,
 'join': 700,
 'part': 1001,
 'sm auction': 1248,
 'auction brand': 74,
 'brand new': 145,
 'new nokia': 936,
 'nokia auction': 946,
 'auction today': 76,
 'today auction': 1396,
 'auction free': 75,
 'free join': 477,
 'join take': 701,
 'take part': 1321,
 'part txt': 1002,
 'txt nokia': 1429,
 'loving': 796,
 'thanks loving': 1352,
 'loving rock': 798,
 'aight': 26,
 'aight head': 27,
 'hey': 630,
 'whats': 1525,
 'sat': 1186,
 'hey whats': 634,
 'whats plan': 1527,
 'plan sat': 1035,
 'chennai': 206,
 'velachery': 1463,
 'chennai velachery': 207,
 'refilled': 1134,
 'successfully': 1303,
 'inr': 686,
 'keralacircle': 712,
 'prepaid': 1060,
 'balance': 94,
 'id': 667,
 'kr': 731,
 'account refilled': 9,
 'refilled successfully': 1135,
 'successfully inr': 1304,
 'inr lt': 687,
 'gt keralacircle': 565,
 'keralacircle prepaid': 713,
 'prepaid account': 1061,
 'account balance': 7,
 'balance lt': 95,
 'gt transaction': 568,
 'transaction id': 1415,
 'id kr': 668,
 'kr lt': 732,
 'voda': 1476,
 'ending': 383,
 'selected': 1196,
 'receive': 1120,
 'award': 79,
 'hava': 605,
 'match': 834,
 'quoting': 1100,
 'code': 234,
 'standard': 1273,
 'app': 55,
 'today voda': 1400,
 'voda number': 1477,
 'number ending': 959,
 'ending selected': 384,
 'selected receive': 1197,
 'receive award': 1121,
 'award hava': 80,
 'hava match': 606,
 'match please': 835,
 'please call': 1041,
 'call quoting': 174,
 'quoting claim': 1101,
 'claim code': 220,
 'code standard': 237,
 'standard rate': 1274,
 'rate app': 1106,
 'next': 938,
 'amazing': 39,
 'picsfree': 1029,
 'video': 1468,
 'sent': 1205,
 'vid': 1466,
 'enough': 388,
 'keyword': 714,
 'next amazing': 939,
 'amazing xxx': 41,
 'xxx picsfree': 1574,
 'picsfree video': 1031,
 'video sent': 1469,
 'sent enjoy': 1206,
 'enjoy one': 386,
 'one vid': 991,
 'vid enough': 1467,
 'enough day': 389,
 'day text': 306,
 'back keyword': 89,
 'keyword picsfree': 715,
 'picsfree get': 1030,
 'get next': 507,
 'next video': 940,
 'sleeping': 1241,
 'nt': 952,
 'feeling': 433,
 'sleeping nt': 1242,
 'nt feeling': 954,
 'feeling well': 435,
 'driving': 357,
 'many': 831,
 'reason': 1117,
 'called': 177,
 'bbd': 102,
 'thts': 1378,
 'chikku': 211,
 'hw': 663,
 'abt': 4,
 'dvg': 361,
 'cold': 238,
 'heard': 613,
 'tht': 1376,
 'vinobanagar': 1470,
 'violence': 1472,
 'condition': 252,
 'ru': 1171,
 'problem': 1078,
 'nt driving': 953,
 'driving even': 358,
 'even many': 400,
 'many reason': 833,
 'reason called': 1118,
 'called bbd': 178,
 'bbd thts': 103,
 'thts chikku': 1379,
 'chikku hw': 212,
 'hw abt': 664,
 'abt dvg': 5,
 'dvg cold': 362,
 'cold heard': 239,
 'heard tht': 614,
 'tht vinobanagar': 1377,
 'vinobanagar violence': 1471,
 'violence hw': 1473,
 'hw condition': 665,
 'condition hw': 253,
 'hw ru': 666,
 'ru problem': 1172,
 'home': 640,
 'morning': 890,
 'dear good': 310,
 'good morning': 545,
 'hey free': 633,
 'th': 1347,
 'gower': 555,
 'wale': 1484,
 'morrow': 892,
 'wk': 1543,
 'random': 1104,
 'th gower': 1348,
 'gower mate': 556,
 'mate man': 838,
 'man good': 828,
 'good wale': 547,
 'wale ill': 1485,
 'ill back': 675,
 'back morrow': 90,
 'morrow wk': 893,
 'wk msg': 1544,
 'msg random': 900,
 'velusamy': 1464,
 'date': 296,
 'birth': 121,
 'company': 248,
 'bank': 96,
 'facility': 421,
 'detail': 330,
 'sir need': 1231,
 'need velusamy': 927,
 'velusamy sir': 1465,
 'sir date': 1229,
 'date birth': 297,
 'birth company': 122,
 'company bank': 249,
 'bank facility': 97,
 'facility detail': 422,
 'winner': 1537,
 'valued': 1459,
 'network': 930,
 'customer': 284,
 'receivea': 1122,
 'reward': 1156,
 'kl': 721,
 'hour': 650,
 'winner valued': 1538,
 'valued network': 1460,
 'network customer': 931,
 'customer selected': 286,
 'selected receivea': 1198,
 'receivea prize': 1123,
 'prize reward': 1075,
 'reward claim': 1157,
 'claim call': 219,
 'call claim': 167,
 'code kl': 236,
 'kl valid': 722,
 'valid hour': 1457,
 'mom': 882,
 'mom want': 883,
 'want know': 1491,
 'lar': 735,
 'anything lar': 51,
 'puppy': 1089,
 'noise': 944,
 'sad puppy': 1176,
 'puppy noise': 1090,
 'aeronautics': 15,
 'professor': 1079,
 'wer': 1519,
 'calld': 175,
 'askd': 67,
 'sit': 1233,
 'aeroplane': 17,
 'aftr': 22,
 'told': 1404,
 'dat': 294,
 'plane': 1037,
 'student': 1295,
 'dey': 331,
 'hurried': 659,
 'move': 895,
 'said': 1178,
 'start': 1275,
 'datz': 298,
 'height confidence': 618,
 'confidence aeronautics': 255,
 'aeronautics professor': 16,
 'professor wer': 1080,
 'wer calld': 1521,
 'calld amp': 176,
 'amp wer': 44,
 'wer askd': 1520,
 'askd sit': 68,
 'sit aeroplane': 1234,
 'aeroplane aftr': 18,
 'aftr sat': 23,
 'sat wer': 1187,
 'wer told': 1522,
 'told dat': 1405,
 'dat plane': 295,
 'plane made': 1039,
 'made student': 817,
 'student dey': 1296,
 'dey hurried': 332,
 'hurried plane': 660,
 'plane bt': 1038,
 'bt didnt': 156,
 'didnt move': 334,
 'move said': 896,
 'said made': 1180,
 'student wont': 1298,
 'wont even': 1547,
 'even start': 401,
 'start datz': 1276,
 'datz confidence': 299,
 'go': 522,
 'urself': 1450,
 'go back': 523,
 'back urself': 92,
 'urself lor': 1451,
 'private': 1070,
 'statement': 1277,
 'show': 1221,
 'unredeemed': 1432,
 'bonus': 140,
 'identifier': 670,
 'expires': 420,
 'private account': 1071,
 'account statement': 10,
 'statement show': 1278,
 'show unredeemed': 1223,
 'unredeemed bonus': 1433,
 'bonus point': 141,
 'point claim': 1049,
 'call identifier': 169,
 'identifier code': 671,
 'code expires': 235,
 'annoying': 45,
 'ok ok': 979,
 'ok whats': 982,
 'whats ur': 1528,
 'ur today': 1447,
 'today plan': 1399,
 'er': 394,
 'hello': 620,
 'quite': 1094,
 'limping': 765,
 'slowly': 1245,
 'followed': 466,
 'aa': 0,
 'exhaust': 416,
 'hanging': 596,
 'er hello': 395,
 'hello thing': 622,
 'thing quite': 1363,
 'quite go': 1095,
 'go plan': 526,
 'plan limping': 1034,
 'limping slowly': 766,
 'slowly home': 1246,
 ...}

## Machine Learning Model Multinomial naive bayes

In [150]:
from sklearn.naive_bayes import MultinomialNB

In [151]:
spam_model_bow=MultinomialNB().fit(X_train,y_train)

In [152]:
y_pred_bow=spam_model_bow.predict(X_test)

In [153]:
from sklearn.metrics import accuracy_score,classification_report

print(accuracy_score(y_test,y_pred_bow))
print(classification_report(y_test,y_pred_bow))

0.9333333333333333
              precision    recall  f1-score   support

       False       0.75      0.75      0.75         4
        True       0.96      0.96      0.96        26

    accuracy                           0.93        30
   macro avg       0.86      0.86      0.86        30
weighted avg       0.93      0.93      0.93        30

## Tf-idf

In [155]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.2)

In [157]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv=TfidfVectorizer(ngram_range=(1,2))

X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [158]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(120, 1789))

In [159]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(30, 1789))

In [160]:
cv.vocabulary_

{'maybe': 844,
 'fat': 427,
 'finger': 452,
 'press': 1064,
 'button': 161,
 'know': 723,
 'maybe fat': 845,
 'fat finger': 428,
 'finger press': 453,
 'press button': 1065,
 'button know': 162,
 'aiyar': 30,
 'poor': 1051,
 'thing': 1359,
 'give': 509,
 'support': 1309,
 'jia': 695,
 'think': 1364,
 'aiyar poor': 31,
 'poor thing': 1052,
 'thing give': 1360,
 'give support': 512,
 'support jia': 1310,
 'jia think': 696,
 'even': 398,
 'friend': 479,
 'priest': 1068,
 'call': 165,
 'even friend': 399,
 'friend priest': 480,
 'priest call': 1069,
 'gudnite': 576,
 'tc': 1332,
 'practice': 1058,
 'going': 533,
 'gudnite tc': 577,
 'tc practice': 1333,
 'practice going': 1059,
 'pls': 1043,
 'send': 1201,
 'mail': 819,
 'relative': 1136,
 'coming': 245,
 'deliver': 324,
 'cost': 264,
 'risk': 1160,
 'benefit': 108,
 'anything': 48,
 'else': 376,
 'thanks': 1351,
 'pls pls': 1044,
 'pls send': 1045,
 'send mail': 1202,
 'mail know': 820,
 'know relative': 727,
 'relative coming': 1137,
 'coming deliver': 247,
 'deliver know': 325,
 'know cost': 724,
 'cost risk': 266,
 'risk benefit': 1161,
 'benefit anything': 109,
 'anything else': 49,
 'else thanks': 379,
 'prepare': 1062,
 'pounded': 1055,
 'every': 404,
 'night': 943,
 'prepare pounded': 1063,
 'pounded every': 1056,
 'every night': 405,
 'babe': 83,
 'miiiiiiissssssssss': 856,
 'need': 923,
 'crave': 272,
 'geeee': 495,
 'sad': 1175,
 'without': 1541,
 'love': 790,
 'babe miiiiiiissssssssss': 86,
 'miiiiiiissssssssss need': 857,
 'need crave': 925,
 'crave geeee': 273,
 'geeee sad': 497,
 'sad without': 1177,
 'without babe': 1542,
 'babe love': 85,
 'dear': 308,
 'shall': 1211,
 'tonite': 1406,
 'busy': 159,
 'street': 1293,
 'update': 1436,
 'looking': 772,
 'ok': 976,
 'varunnathu': 1461,
 'edukkukayee': 372,
 'raksha': 1102,
 'ollu': 985,
 'good': 540,
 'one': 987,
 'real': 1113,
 'sense': 1204,
 'dear shall': 312,
 'shall mail': 1212,
 'mail tonite': 821,
 'tonite busy': 1407,
 'busy street': 160,
 'street shall': 1294,
 'shall update': 1213,
 'update tonite': 1439,
 'tonite thing': 1408,
 'thing looking': 1361,
 'looking ok': 774,
 'ok varunnathu': 981,
 'varunnathu edukkukayee': 1462,
 'edukkukayee raksha': 373,
 'raksha ollu': 1103,
 'ollu good': 986,
 'good one': 546,
 'one real': 990,
 'real sense': 1114,
 'nd': 921,
 'time': 1382,
 'tried': 1419,
 'contact': 257,
 'pound': 1053,
 'prize': 1072,
 'claim': 218,
 'easy': 364,
 'per': 1014,
 'minute': 863,
 'bt': 155,
 'national': 919,
 'rate': 1105,
 'nd time': 922,
 'time tried': 1387,
 'tried contact': 1420,
 'contact pound': 258,
 'pound prize': 1054,
 'prize claim': 1073,
 'claim easy': 221,
 'easy call': 365,
 'call per': 173,
 'per minute': 1016,
 'minute bt': 865,
 'bt national': 158,
 'national rate': 920,
 'message': 851,
 'free': 474,
 'welcome': 1507,
 'new': 934,
 'improved': 681,
 'sex': 1209,
 'dogging': 346,
 'club': 229,
 'unsubscribe': 1434,
 'service': 1207,
 'reply': 1152,
 'stop': 1288,
 'msg': 897,
 'message free': 852,
 'free welcome': 478,
 'welcome new': 1508,
 'new improved': 935,
 'improved sex': 682,
 'sex dogging': 1210,
 'dogging club': 347,
 'club unsubscribe': 230,
 'unsubscribe service': 1435,
 'service reply': 1208,
 'reply stop': 1153,
 'stop msg': 1290,
 'oh': 972,
 'god': 531,
 'found': 472,
 'number': 957,
 'glad': 514,
 'text': 1342,
 'back': 87,
 'xafter': 1570,
 'cst': 280,
 'std': 1279,
 'ntwk': 955,
 'chg': 208,
 'oh god': 974,
 'god found': 532,
 'found number': 473,
 'number glad': 960,
 'glad text': 516,
 'text back': 1343,
 'back xafter': 93,
 'xafter msg': 1571,
 'msg cst': 899,
 'cst std': 281,
 'std ntwk': 1280,
 'ntwk chg': 956,
 'watching': 1499,
 'live': 769,
 'watching live': 1500,
 'ur': 1442,
 'change': 201,
 'da': 289,
 'report': 1154,
 'big': 116,
 'co': 231,
 'already': 32,
 'made': 814,
 'previous': 1066,
 'ur change': 1443,
 'change da': 202,
 'da report': 293,
 'report big': 1155,
 'big co': 117,
 'co already': 232,
 'already made': 34,
 'made change': 815,
 'da previous': 292,
 'previous report': 1067,
 'december': 313,
 'mobile': 876,
 'mths': 903,
 'entitled': 391,
 'latest': 740,
 'colour': 242,
 'camera': 179,
 'december mobile': 314,
 'mobile mths': 879,
 'mths entitled': 905,
 'entitled update': 392,
 'update latest': 1438,
 'latest colour': 741,
 'colour camera': 243,
 'camera mobile': 180,
 'mobile free': 878,
 'free call': 475,
 'call mobile': 171,
 'mobile update': 881,
 'update co': 1437,
 'co free': 233,
 'bill': 118,
 'letter': 749,
 'expecting': 418,
 'orange': 992,
 'may': 841,
 'still': 1281,
 'say': 1188,
 'bill letter': 119,
 'letter expecting': 750,
 'expecting one': 419,
 'one orange': 989,
 'orange bill': 993,
 'bill may': 120,
 'may still': 843,
 'still say': 1286,
 'say orange': 1191,
 'cool': 261,
 'head': 609,
 'cool text': 263,
 'text head': 1346,
 'taking': 1326,
 'half': 592,
 'day': 300,
 'leave': 742,
 'bec': 104,
 'well': 1509,
 'taking half': 1327,
 'half day': 593,
 'day leave': 303,
 'leave bec': 743,
 'bec well': 105,
 'neft': 928,
 'transaction': 1414,
 'reference': 1132,
 'lt': 803,
 'gt': 562,
 'decimal': 318,
 'credited': 274,
 'beneficiary': 106,
 'account': 6,
 'neft transaction': 929,
 'transaction reference': 1416,
 'reference number': 1133,
 'number lt': 962,
 'lt gt': 805,
 'gt lt': 566,
 'lt decimal': 804,
 'decimal gt': 319,
 'gt credited': 564,
 'credited beneficiary': 275,
 'beneficiary account': 107,
 'account lt': 8,
 'lt time': 806,
 'time gt': 1385,
 'jus': 705,
 'finish': 454,
 'blowing': 129,
 'hair': 590,
 'dinner': 340,
 'jus finish': 706,
 'finish blowing': 455,
 'blowing hair': 130,
 'hair finish': 591,
 'finish dinner': 456,
 'dinner already': 341,
 'gei': 498,
 'happend': 597,
 'tron': 1421,
 'ill': 674,
 'dl': 343,
 'oh gei': 973,
 'gei happend': 499,
 'happend tron': 598,
 'tron maybe': 1422,
 'maybe ill': 846,
 'ill dl': 676,
 'height': 617,
 'shit': 1216,
 'situation': 1237,
 'guy': 583,
 'throw': 1374,
 'luv': 812,
 'gal': 486,
 'fall': 425,
 'brother': 152,
 'who': 1530,
 'gay': 490,
 'height oh': 619,
 'oh shit': 975,
 'shit situation': 1217,
 'situation guy': 1238,
 'guy throw': 584,
 'throw luv': 1375,
 'luv letter': 813,
 'letter gal': 751,
 'gal fall': 487,
 'fall brother': 426,
 'brother head': 154,
 'head who': 610,
 'who gay': 1531,
 'might': 853,
 'want': 1490,
 'pull': 1087,
 'case': 192,
 'plan': 1033,
 'spending': 1268,
 'much': 907,
 'confidence': 254,
 'derek': 328,
 'taylor': 1330,
 'money': 884,
 'management': 829,
 'might want': 855,
 'want pull': 1492,
 'pull case': 1088,
 'case plan': 193,
 'plan spending': 1036,
 'spending much': 1269,
 'much confidence': 908,
 'confidence derek': 256,
 'derek taylor': 329,
 'taylor money': 1331,
 'money management': 885,
 'roger': 1167,
 'probably': 1076,
 'rem': 1141,
 'roger probably': 1168,
 'probably going': 1077,
 'going rem': 537,
 'happy': 599,
 'year': 1582,
 'man': 826,
 'happy new': 600,
 'new year': 937,
 'year man': 1583,
 'hi': 635,
 'hope': 642,
 'get': 502,
 'txt': 1427,
 'journey': 703,
 'hasnt': 601,
 'gd': 491,
 'min': 858,
 'late': 736,
 'hi hope': 636,
 'hope get': 644,
 'get txt': 508,
 'txt journey': 1428,
 'journey hasnt': 704,
 'hasnt gd': 602,
 'gd min': 492,
 'min late': 859,
 'late think': 738,
 'urgent': 1448,
 'awarded': 81,
 'guaranteed': 570,
 'land': 733,
 'line': 767,
 'valid': 1456,
 'hr': 653,
 'ppm': 1057,
 'urgent mobile': 1449,
 'mobile number': 880,
 'number awarded': 958,
 'awarded prize': 82,
 'prize guaranteed': 1074,
 'guaranteed call': 571,
 'call land': 170,
 'land line': 734,
 'line claim': 768,
 'claim valid': 223,
 'valid hr': 1458,
 'hr ppm': 654,
 'rock': 1165,
 'yr': 1590,
 'chik': 209,
 'filthy': 446,
 'film': 442,
 'xxx': 1572,
 'pic': 1024,
 'phone': 1019,
 'rply': 1169,
 'filth': 444,
 'saristar': 1182,
 'ltd': 807,
 'yt': 1594,
 'cancel': 182,
 'rock yr': 1166,
 'yr chik': 1591,
 'chik get': 210,
 'get filthy': 505,
 'filthy film': 447,
 'film xxx': 443,
 'xxx pic': 1573,
 'pic yr': 1026,
 'yr phone': 1593,
 'phone rply': 1020,
 'rply filth': 1170,
 'filth saristar': 445,
 'saristar ltd': 1183,
 'ltd yt': 808,
 'yt per': 1595,
 'per day': 1015,
 'day stop': 305,
 'stop cancel': 1289,
 'creepy': 276,
 'like': 757,
 'forgot': 471,
 'text creepy': 1345,
 'creepy like': 277,
 'like think': 762,
 'think forgot': 1365,
 'reached': 1111,
 'reached already': 1112,
 'yeah': 1577,
 'rite': 1162,
 'yeah jus': 1578,
 'jus rite': 707,
 'evening': 402,
 'sir': 1228,
 'nice': 941,
 'wanted': 1493,
 'bring': 147,
 'notice': 950,
 'paying': 1010,
 'rent': 1146,
 'past': 1003,
 'month': 886,
 'pay': 1005,
 'charge': 203,
 'felt': 436,
 'would': 1560,
 'inconsiderate': 683,
 'nag': 915,
 'something': 1254,
 'great': 559,
 'didnt': 333,
 'speak': 1264,
 'however': 651,
 'recession': 1126,
 'wont': 1545,
 'able': 2,
 'hence': 626,
 'askin': 69,
 'ahead': 24,
 'end': 380,
 'please': 1040,
 'help': 623,
 'thank': 1349,
 'everything': 406,
 'good evening': 541,
 'evening sir': 403,
 'sir hope': 1230,
 'hope nice': 646,
 'nice day': 942,
 'day wanted': 307,
 'wanted bring': 1494,
 'bring notice': 148,
 'notice late': 951,
 'late paying': 737,
 'paying rent': 1011,
 'rent past': 1147,
 'past month': 1004,
 'month pay': 889,
 'pay lt': 1009,
 'gt charge': 563,
 'charge felt': 204,
 'felt would': 437,
 'would inconsiderate': 1561,
 'inconsiderate nag': 684,
 'nag something': 916,
 'something give': 1255,
 'give great': 510,
 'great cost': 560,
 'cost didnt': 265,
 'didnt speak': 335,
 'speak however': 1265,
 'however recession': 652,
 'recession wont': 1127,
 'wont able': 1546,
 'able pay': 3,
 'pay charge': 1006,
 'charge month': 205,
 'month hence': 888,
 'hence askin': 627,
 'askin well': 70,
 'well ahead': 1510,
 'ahead month': 25,
 'month end': 887,
 'end please': 381,
 'please help': 1042,
 'help thank': 625,
 'thank everything': 1350,
 'sure': 1311,
 'mate': 836,
 'haunt': 603,
 'got': 548,
 'stuff': 1301,
 'sorted': 1260,
 'im': 679,
 'sound': 1262,
 'anyway': 53,
 'promoting': 1083,
 'hex': 628,
 'way': 1501,
 'dont': 350,
 'joke': 702,
 'yeah sure': 1580,
 'sure thing': 1313,
 'thing mate': 1362,
 'mate haunt': 837,
 'haunt got': 604,
 'got stuff': 550,
 'stuff sorted': 1302,
 'sorted im': 1261,
 'im going': 680,
 'going sound': 538,
 'sound anyway': 1263,
 'anyway promoting': 54,
 'promoting hex': 1084,
 'hex way': 629,
 'way dont': 1504,
 'dont know': 352,
 'know number': 726,
 'number joke': 961,
 'wow': 1564,
 'healthy': 611,
 'old': 983,
 'airport': 28,
 'rd': 1109,
 'lor': 777,
 'cant': 183,
 'thk': 1370,
 'bathing': 100,
 'dog': 344,
 'later': 739,
 'wow healthy': 1565,
 'healthy old': 612,
 'old airport': 984,
 'airport rd': 29,
 'rd lor': 1110,
 'lor cant': 779,
 'cant thk': 185,
 'thk anything': 1371,
 'else bathing': 377,
 'bathing dog': 101,
 'dog later': 345,
 'fighting': 438,
 'world': 1550,
 'either': 374,
 'win': 1534,
 'lose': 782,
 'fightng': 440,
 'close': 227,
 'dificult': 338,
 'fighting world': 439,
 'world easy': 1551,
 'easy either': 366,
 'either win': 375,
 'win lose': 1535,
 'lose bt': 783,
 'bt fightng': 157,
 'fightng close': 441,
 'close dificult': 228,
 'dificult lose': 339,
 'lose lose': 784,
 'lose win': 785,
 'win still': 1536,
 'still lose': 1285,
 'take': 1319,
 'enjoy': 385,
 'ok take': 980,
 'take ur': 1325,
 'ur time': 1446,
 'time enjoy': 1383,
 'enjoy ur': 387,
 'ur dinner': 1444,
 'actually': 13,
 'fuck': 481,
 'whatever': 1523,
 'find': 448,
 'excuse': 414,
 'tampa': 1328,
 'point': 1048,
 'january': 691,
 'though': 1373,
 'actually fuck': 14,
 'fuck whatever': 482,
 'whatever find': 1524,
 'find excuse': 449,
 'excuse tampa': 415,
 'tampa point': 1329,
 'point january': 1050,
 'january though': 692,
 'couple': 269,
 'amp': 42,
 'let': 747,
 'mu': 906,
 'yeah leave': 1579,
 'leave couple': 744,
 'couple minute': 270,
 'minute amp': 864,
 'amp let': 43,
 'let know': 748,
 'know get': 725,
 'get mu': 506,
 'difficult': 336,
 'pay like': 1008,
 'like lt': 760,
 'gt yr': 569,
 'yr difficult': 1592,
 'lmao': 770,
 'lmao take': 771,
 'take pic': 1322,
 'pic send': 1025,
 'puzzeles': 1091,
 'management puzzeles': 830,
 'walk': 1487,
 'give time': 513,
 'time walk': 1388,
 'job': 697,
 'entrepreneur': 393,
 'good good': 542,
 'good job': 544,
 'job like': 698,
 'like entrepreneur': 758,
 'reminder': 1144,
 'downloaded': 353,
 'content': 259,
 'paid': 998,
 'goto': 553,
 'http': 655,
 'doit': 348,
 'mymoby': 913,
 'tv': 1425,
 'collect': 240,
 'reminder downloaded': 1145,
 'downloaded content': 354,
 'content already': 260,
 'already paid': 35,
 'paid goto': 999,
 'goto http': 554,
 'http doit': 656,
 'doit mymoby': 349,
 'mymoby tv': 914,
 'tv collect': 1426,
 'collect content': 241,
 'sm': 1247,
 'auction': 73,
 'brand': 144,
 'nokia': 945,
 'today': 1395,
 'join': 700,
 'part': 1001,
 'sm auction': 1248,
 'auction brand': 74,
 'brand new': 145,
 'new nokia': 936,
 'nokia auction': 946,
 'auction today': 76,
 'today auction': 1396,
 'auction free': 75,
 'free join': 477,
 'join take': 701,
 'take part': 1321,
 'part txt': 1002,
 'txt nokia': 1429,
 'loving': 796,
 'thanks loving': 1352,
 'loving rock': 798,
 'aight': 26,
 'aight head': 27,
 'hey': 630,
 'whats': 1525,
 'sat': 1186,
 'hey whats': 634,
 'whats plan': 1527,
 'plan sat': 1035,
 'chennai': 206,
 'velachery': 1463,
 'chennai velachery': 207,
 'refilled': 1134,
 'successfully': 1303,
 'inr': 686,
 'keralacircle': 712,
 'prepaid': 1060,
 'balance': 94,
 'id': 667,
 'kr': 731,
 'account refilled': 9,
 'refilled successfully': 1135,
 'successfully inr': 1304,
 'inr lt': 687,
 'gt keralacircle': 565,
 'keralacircle prepaid': 713,
 'prepaid account': 1061,
 'account balance': 7,
 'balance lt': 95,
 'gt transaction': 568,
 'transaction id': 1415,
 'id kr': 668,
 'kr lt': 732,
 'voda': 1476,
 'ending': 383,
 'selected': 1196,
 'receive': 1120,
 'award': 79,
 'hava': 605,
 'match': 834,
 'quoting': 1100,
 'code': 234,
 'standard': 1273,
 'app': 55,
 'today voda': 1400,
 'voda number': 1477,
 'number ending': 959,
 'ending selected': 384,
 'selected receive': 1197,
 'receive award': 1121,
 'award hava': 80,
 'hava match': 606,
 'match please': 835,
 'please call': 1041,
 'call quoting': 174,
 'quoting claim': 1101,
 'claim code': 220,
 'code standard': 237,
 'standard rate': 1274,
 'rate app': 1106,
 'next': 938,
 'amazing': 39,
 'picsfree': 1029,
 'video': 1468,
 'sent': 1205,
 'vid': 1466,
 'enough': 388,
 'keyword': 714,
 'next amazing': 939,
 'amazing xxx': 41,
 'xxx picsfree': 1574,
 'picsfree video': 1031,
 'video sent': 1469,
 'sent enjoy': 1206,
 'enjoy one': 386,
 'one vid': 991,
 'vid enough': 1467,
 'enough day': 389,
 'day text': 306,
 'back keyword': 89,
 'keyword picsfree': 715,
 'picsfree get': 1030,
 'get next': 507,
 'next video': 940,
 'sleeping': 1241,
 'nt': 952,
 'feeling': 433,
 'sleeping nt': 1242,
 'nt feeling': 954,
 'feeling well': 435,
 'driving': 357,
 'many': 831,
 'reason': 1117,
 'called': 177,
 'bbd': 102,
 'thts': 1378,
 'chikku': 211,
 'hw': 663,
 'abt': 4,
 'dvg': 361,
 'cold': 238,
 'heard': 613,
 'tht': 1376,
 'vinobanagar': 1470,
 'violence': 1472,
 'condition': 252,
 'ru': 1171,
 'problem': 1078,
 'nt driving': 953,
 'driving even': 358,
 'even many': 400,
 'many reason': 833,
 'reason called': 1118,
 'called bbd': 178,
 'bbd thts': 103,
 'thts chikku': 1379,
 'chikku hw': 212,
 'hw abt': 664,
 'abt dvg': 5,
 'dvg cold': 362,
 'cold heard': 239,
 'heard tht': 614,
 'tht vinobanagar': 1377,
 'vinobanagar violence': 1471,
 'violence hw': 1473,
 'hw condition': 665,
 'condition hw': 253,
 'hw ru': 666,
 'ru problem': 1172,
 'home': 640,
 'morning': 890,
 'dear good': 310,
 'good morning': 545,
 'hey free': 633,
 'th': 1347,
 'gower': 555,
 'wale': 1484,
 'morrow': 892,
 'wk': 1543,
 'random': 1104,
 'th gower': 1348,
 'gower mate': 556,
 'mate man': 838,
 'man good': 828,
 'good wale': 547,
 'wale ill': 1485,
 'ill back': 675,
 'back morrow': 90,
 'morrow wk': 893,
 'wk msg': 1544,
 'msg random': 900,
 'velusamy': 1464,
 'date': 296,
 'birth': 121,
 'company': 248,
 'bank': 96,
 'facility': 421,
 'detail': 330,
 'sir need': 1231,
 'need velusamy': 927,
 'velusamy sir': 1465,
 'sir date': 1229,
 'date birth': 297,
 'birth company': 122,
 'company bank': 249,
 'bank facility': 97,
 'facility detail': 422,
 'winner': 1537,
 'valued': 1459,
 'network': 930,
 'customer': 284,
 'receivea': 1122,
 'reward': 1156,
 'kl': 721,
 'hour': 650,
 'winner valued': 1538,
 'valued network': 1460,
 'network customer': 931,
 'customer selected': 286,
 'selected receivea': 1198,
 'receivea prize': 1123,
 'prize reward': 1075,
 'reward claim': 1157,
 'claim call': 219,
 'call claim': 167,
 'code kl': 236,
 'kl valid': 722,
 'valid hour': 1457,
 'mom': 882,
 'mom want': 883,
 'want know': 1491,
 'lar': 735,
 'anything lar': 51,
 'puppy': 1089,
 'noise': 944,
 'sad puppy': 1176,
 'puppy noise': 1090,
 'aeronautics': 15,
 'professor': 1079,
 'wer': 1519,
 'calld': 175,
 'askd': 67,
 'sit': 1233,
 'aeroplane': 17,
 'aftr': 22,
 'told': 1404,
 'dat': 294,
 'plane': 1037,
 'student': 1295,
 'dey': 331,
 'hurried': 659,
 'move': 895,
 'said': 1178,
 'start': 1275,
 'datz': 298,
 'height confidence': 618,
 'confidence aeronautics': 255,
 'aeronautics professor': 16,
 'professor wer': 1080,
 'wer calld': 1521,
 'calld amp': 176,
 'amp wer': 44,
 'wer askd': 1520,
 'askd sit': 68,
 'sit aeroplane': 1234,
 'aeroplane aftr': 18,
 'aftr sat': 23,
 'sat wer': 1187,
 'wer told': 1522,
 'told dat': 1405,
 'dat plane': 295,
 'plane made': 1039,
 'made student': 817,
 'student dey': 1296,
 'dey hurried': 332,
 'hurried plane': 660,
 'plane bt': 1038,
 'bt didnt': 156,
 'didnt move': 334,
 'move said': 896,
 'said made': 1180,
 'student wont': 1298,
 'wont even': 1547,
 'even start': 401,
 'start datz': 1276,
 'datz confidence': 299,
 'go': 522,
 'urself': 1450,
 'go back': 523,
 'back urself': 92,
 'urself lor': 1451,
 'private': 1070,
 'statement': 1277,
 'show': 1221,
 'unredeemed': 1432,
 'bonus': 140,
 'identifier': 670,
 'expires': 420,
 'private account': 1071,
 'account statement': 10,
 'statement show': 1278,
 'show unredeemed': 1223,
 'unredeemed bonus': 1433,
 'bonus point': 141,
 'point claim': 1049,
 'call identifier': 169,
 'identifier code': 671,
 'code expires': 235,
 'annoying': 45,
 'ok ok': 979,
 'ok whats': 982,
 'whats ur': 1528,
 'ur today': 1447,
 'today plan': 1399,
 'er': 394,
 'hello': 620,
 'quite': 1094,
 'limping': 765,
 'slowly': 1245,
 'followed': 466,
 'aa': 0,
 'exhaust': 416,
 'hanging': 596,
 'er hello': 395,
 'hello thing': 622,
 'thing quite': 1363,
 'quite go': 1095,
 'go plan': 526,
 'plan limping': 1034,
 'limping slowly': 766,
 'slowly home': 1246,
 ...}

In [165]:
from sklearn.naive_bayes import MultinomialNB

spam_tfidf_model=MultinomialNB().fit(X_train,y_train)

In [166]:
y_pred_tfidf=spam_tfidf_model.predict(X_test)

In [167]:
print(accuracy_score(y_test,y_pred_tfidf))

1.0

In [168]:
print(classification_report(y_test,y_pred_tfidf))

              precision    recall  f1-score   support

        True       1.00      1.00      1.00        30

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30